name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # needs: [set-vars, unit-tests, spot-bugs, integration-tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # Amazon version see Dockerfile
          java-version: '21'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.5 # this is probably not needed on the github ubuntu
      - name: Build Artifact by Maven
        run: mvn clean package -DskipTest

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
           registry: 'ghcr.io'
           username: ${{ github.actor}}
           password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true #push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tag_with_ref: true
          tags: ghcr.io/${{ github.repository }}/app:latest
