name: Build

on: [push]




jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    # needs: [set-vars, unit-tests, spot-bugs, integration-tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # Amazon version see Dockerfile
          java-version: '21'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.5 # this is probably not needed on the github ubuntu
      - name: Build Artifact by Maven
        run: mvn clean package -DskipTest

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
           registry: 'ghcr.io'
           username: ${{ github.actor}}
           password: ${{ secrets.GITHUB_TOKEN }}
           # BEWARE THIS WILL NOT WORK unless you create a credentails and put them in the settings a
           # better use
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true #push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tag_with_ref: true
          tags: ${{ github.repository }}/app:latest
