name: Build

on: [push]

env:
  DISTRIBUTION: 'corretto' # amazon version
  JAVA_VERSION: 21

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${ env.DISTRIBUTION }
          java-version: ${ env.JAVA_VERSION }
      - name: Run unit tests
        run: mvn -s ${MAVEN_SETTINGS_FILE} clean test
      - name: Create coverage report files
        run:
          mvn jacoco:report
      - name: Upload code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-file
          path: target/site/jacoco/jacoco.xml
  build:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            distribution: ${ env.DISTRIBUTION }
            java-version: ${ env.JAVA_VERSION }
      - name: Build Artifact by Maven
        run: mvn clean package -DskipTests=true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
           registry: 'ghcr.io'
           username: ${{ github.actor}}
           password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true #push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tag_with_ref: true
          tags: ghcr.io/${{ github.repository }}/app:latest
